name: Playwright E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:${{ fromJson(github.workspace == '' && '14' || fromJson(readFile('.github/workflow-config.json')).postgres.version }}
        env:
          POSTGRES_USER: ${{ fromJson(github.workspace == '' && 'postgres' || fromJson(readFile('.github/workflow-config.json')).postgres.user }}
          POSTGRES_PASSWORD: ${{ fromJson(github.workspace == '' && 'postgres' || fromJson(readFile('.github/workflow-config.json')).postgres.password }}
          POSTGRES_DB: ${{ fromJson(github.workspace == '' && 'crm_test' || fromJson(readFile('.github/workflow-config.json')).postgres.db_name }}
        ports:
          - ${{ fromJson(github.workspace == '' && '5432:5432' || fromJson(readFile('.github/workflow-config.json')).postgres.port + ':' + fromJson(readFile('.github/workflow-config.json')).postgres.port }}
        options: >-
          --health-cmd pg_isready
          --health-interval ${{ fromJson(github.workspace == '' && '10s' || fromJson(readFile('.github/workflow-config.json')).postgres.health_interval }}
          --health-timeout ${{ fromJson(github.workspace == '' && '5s' || fromJson(readFile('.github/workflow-config.json')).postgres.health_timeout }}
          --health-retries ${{ fromJson(github.workspace == '' && '5' || fromJson(readFile('.github/workflow-config.json')).postgres.health_retries }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ fromJson(github.workspace == '' && '3.9' || fromJson(readFile('.github/workflow-config.json')).python_version }}
          
      - name: Install Python dependencies
        working-directory: ./simple-crm
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ fromJson(github.workspace == '' && '16' || fromJson(readFile('.github/workflow-config.json')).node_version }}
      
      - name: Install Playwright
        working-directory: ./simple-crm
        run: |
          npm init -y
          npm install -D @playwright/test
          npx playwright install --with-deps chromium
      
      - name: Run Playwright tests
        working-directory: ./simple-crm
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/crm_test
          BASE_URL: http://localhost:5000
        run: |
          npx playwright test
      
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./simple-crm/playwright-report
          retention-days: 30