name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./simple-crm
          file: ./simple-crm/Dockerfile
          push: false
          tags: simple-crm-demo:latest
